"""initial schema

Revision ID: 1c61df536704
Revises:
Create Date: 2026-04-20 23:40:09.411595
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import redteam_mcp.domain.storage  # noqa: F401 — referenced below for UUIDString column type

# revision identifiers, used by Alembic.
revision: str = "1c61df536704"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "engagements",
        sa.Column("id", redteam_mcp.domain.storage.UUIDString(length=36), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PLANNING", "ACTIVE", "PAUSED", "CLOSED", name="engagement_status"),
            nullable=False,
        ),
        sa.Column(
            "engagement_type",
            sa.Enum(
                "PENTEST",
                "RED_TEAM",
                "CTF",
                "RESEARCH",
                "BUG_BOUNTY",
                "INTERNAL_TRAINING",
                name="engagement_type",
            ),
            nullable=False,
        ),
        sa.Column("client", sa.String(length=128), nullable=False),
        sa.Column("owners_json", sa.JSON(), nullable=False),
        sa.Column("authorization_doc_ref", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dry_run", sa.Boolean(), nullable=False),
        sa.Column("opsec_mode", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_engagements_name"), "engagements", ["name"], unique=True)
    op.create_table(
        "artifacts",
        sa.Column("id", redteam_mcp.domain.storage.UUIDString(length=36), nullable=False),
        sa.Column(
            "engagement_id", redteam_mcp.domain.storage.UUIDString(length=36), nullable=False
        ),
        sa.Column(
            "kind",
            sa.Enum(
                "PAYLOAD",
                "CRED_DUMP",
                "PACKET_CAPTURE",
                "SCREENSHOT",
                "LOG",
                "REPORT",
                "BLOODHOUND_DATA",
                "HTTP_REQUEST_RESPONSE",
                "SHELLCODE",
                "MALWARE_SAMPLE",
                "OTHER",
                name="artifact_kind",
            ),
            nullable=False,
        ),
        sa.Column("storage_path", sa.String(length=1024), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("encrypted", sa.Boolean(), nullable=False),
        sa.Column("produced_by_tool", sa.String(length=128), nullable=False),
        sa.Column("produced_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "source_target_id", redteam_mcp.domain.storage.UUIDString(length=36), nullable=True
        ),
        sa.Column("mime_type", sa.String(length=128), nullable=False),
        sa.Column("original_filename", sa.String(length=512), nullable=True),
        sa.Column("tags_json", sa.JSON(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["engagement_id"], ["engagements.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_artifacts_engagement_id"), "artifacts", ["engagement_id"], unique=False
    )
    op.create_index(op.f("ix_artifacts_sha256"), "artifacts", ["sha256"], unique=False)
    op.create_table(
        "scopes",
        sa.Column("id", redteam_mcp.domain.storage.UUIDString(length=36), nullable=False),
        sa.Column(
            "engagement_id", redteam_mcp.domain.storage.UUIDString(length=36), nullable=False
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["engagement_id"], ["engagements.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("engagement_id"),
    )
    op.create_table(
        "targets",
        sa.Column("id", redteam_mcp.domain.storage.UUIDString(length=36), nullable=False),
        sa.Column(
            "engagement_id", redteam_mcp.domain.storage.UUIDString(length=36), nullable=False
        ),
        sa.Column(
            "kind",
            sa.Enum(
                "DOMAIN",
                "SUBDOMAIN",
                "HOSTNAME",
                "IPV4",
                "IPV6",
                "URL",
                "EMAIL",
                "PERSON",
                "ORGANIZATION",
                "APPLICATION",
                "NETWORK",
                name="target_kind",
            ),
            nullable=False,
        ),
        sa.Column("value", sa.String(length=512), nullable=False),
        sa.Column("parent_id", redteam_mcp.domain.storage.UUIDString(length=36), nullable=True),
        sa.Column("discovered_by_tool", sa.String(length=128), nullable=True),
        sa.Column("discovered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("open_ports_json", sa.JSON(), nullable=False),
        sa.Column("tech_stack_json", sa.JSON(), nullable=False),
        sa.Column("hostnames_json", sa.JSON(), nullable=False),
        sa.Column("organization", sa.String(length=256), nullable=True),
        sa.Column("country", sa.String(length=8), nullable=True),
        sa.Column("last_scanned_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("tags_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["engagement_id"], ["engagements.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_id"], ["targets.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_targets_engagement_id"), "targets", ["engagement_id"], unique=False)
    op.create_index(op.f("ix_targets_value"), "targets", ["value"], unique=False)
    op.create_table(
        "tool_invocations",
        sa.Column("id", redteam_mcp.domain.storage.UUIDString(length=36), nullable=False),
        sa.Column(
            "engagement_id", redteam_mcp.domain.storage.UUIDString(length=36), nullable=False
        ),
        sa.Column("actor_id", redteam_mcp.domain.storage.UUIDString(length=36), nullable=False),
        sa.Column("tool_name", sa.String(length=128), nullable=False),
        sa.Column("arguments_sanitized_json", sa.JSON(), nullable=False),
        sa.Column("arguments_hash", sa.String(length=64), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("truncated", sa.Boolean(), nullable=False),
        sa.Column("timed_out", sa.Boolean(), nullable=False),
        sa.Column("findings_created_json", sa.JSON(), nullable=False),
        sa.Column("credentials_created_json", sa.JSON(), nullable=False),
        sa.Column("artifacts_created_json", sa.JSON(), nullable=False),
        sa.Column("targets_created_json", sa.JSON(), nullable=False),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("prev_hash", sa.String(length=64), nullable=False),
        sa.Column("this_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["engagement_id"], ["engagements.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("this_hash"),
    )
    op.create_index(
        op.f("ix_tool_invocations_actor_id"), "tool_invocations", ["actor_id"], unique=False
    )
    op.create_index(
        op.f("ix_tool_invocations_engagement_id"),
        "tool_invocations",
        ["engagement_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_tool_invocations_started_at"), "tool_invocations", ["started_at"], unique=False
    )
    op.create_index(
        op.f("ix_tool_invocations_tool_name"), "tool_invocations", ["tool_name"], unique=False
    )
    op.create_table(
        "credentials",
        sa.Column("id", redteam_mcp.domain.storage.UUIDString(length=36), nullable=False),
        sa.Column(
            "engagement_id", redteam_mcp.domain.storage.UUIDString(length=36), nullable=False
        ),
        sa.Column(
            "kind",
            sa.Enum(
                "PASSWORD_PLAINTEXT",
                "NTLM_HASH",
                "NETNTLMV2_HASH",
                "KERBEROS_TGT",
                "KERBEROS_TGS",
                "KERBEROS_AS_REP",
                "JWT",
                "SESSION_COOKIE",
                "API_KEY",
                "SSH_PRIVATE_KEY",
                "CLOUD_ACCESS_KEY",
                "OTHER",
                name="credential_kind",
            ),
            nullable=False,
        ),
        sa.Column("target_id", redteam_mcp.domain.storage.UUIDString(length=36), nullable=True),
        sa.Column("obtained_from_tool", sa.String(length=128), nullable=False),
        sa.Column("obtained_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("identity", sa.String(length=256), nullable=False),
        sa.Column("secret_ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("secret_kdf", sa.String(length=64), nullable=False),
        sa.Column("secret_metadata_json", sa.JSON(), nullable=False),
        sa.Column("validated", sa.Boolean(), nullable=False),
        sa.Column("validated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("tags_json", sa.JSON(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(["engagement_id"], ["engagements.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_id"], ["targets.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_credentials_engagement_id"), "credentials", ["engagement_id"], unique=False
    )
    op.create_table(
        "findings",
        sa.Column("id", redteam_mcp.domain.storage.UUIDString(length=36), nullable=False),
        sa.Column(
            "engagement_id", redteam_mcp.domain.storage.UUIDString(length=36), nullable=False
        ),
        sa.Column("target_id", redteam_mcp.domain.storage.UUIDString(length=36), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column(
            "severity",
            sa.Enum("INFO", "LOW", "MEDIUM", "HIGH", "CRITICAL", name="finding_severity"),
            nullable=False,
        ),
        sa.Column(
            "confidence",
            sa.Enum("SUSPECTED", "LIKELY", "CONFIRMED", name="confidence"),
            nullable=False,
        ),
        sa.Column(
            "category",
            sa.Enum(
                "INJECTION",
                "BROKEN_AUTH",
                "SENSITIVE_DATA",
                "MISCONFIGURATION",
                "VULNERABLE_COMPONENT",
                "ACCESS_CONTROL",
                "CRYPTOGRAPHY",
                "LOGIC_FLAW",
                "INFORMATION_DISCLOSURE",
                "SOCIAL_ENGINEERING",
                "SUPPLY_CHAIN",
                "OTHER",
                name="finding_category",
            ),
            nullable=False,
        ),
        sa.Column("cwe_json", sa.JSON(), nullable=False),
        sa.Column("cve_json", sa.JSON(), nullable=False),
        sa.Column("owasp_top10_json", sa.JSON(), nullable=False),
        sa.Column("mitre_attack_json", sa.JSON(), nullable=False),
        sa.Column("cvss_vector", sa.String(length=128), nullable=True),
        sa.Column("cvss_score", sa.Float(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("impact", sa.Text(), nullable=False),
        sa.Column("remediation", sa.Text(), nullable=False),
        sa.Column("references_json", sa.JSON(), nullable=False),
        sa.Column("evidence_json", sa.JSON(), nullable=False),
        sa.Column("discovered_by_tool", sa.String(length=128), nullable=False),
        sa.Column("discovered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("verified_by", redteam_mcp.domain.storage.UUIDString(length=36), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "NEW",
                "TRIAGED",
                "CONFIRMED",
                "FIXED",
                "CLOSED_WONTFIX",
                "FALSE_POSITIVE",
                name="finding_status",
            ),
            nullable=False,
        ),
        sa.Column("triage_notes", sa.Text(), nullable=False),
        sa.Column("fixed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("group_id", redteam_mcp.domain.storage.UUIDString(length=36), nullable=True),
        sa.ForeignKeyConstraint(["engagement_id"], ["engagements.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_id"], ["targets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_findings_discovered_at"), "findings", ["discovered_at"], unique=False)
    op.create_index(op.f("ix_findings_engagement_id"), "findings", ["engagement_id"], unique=False)
    op.create_index(op.f("ix_findings_severity"), "findings", ["severity"], unique=False)
    op.create_index(op.f("ix_findings_status"), "findings", ["status"], unique=False)
    op.create_index(op.f("ix_findings_target_id"), "findings", ["target_id"], unique=False)
    op.create_table(
        "scope_entries",
        sa.Column("id", redteam_mcp.domain.storage.UUIDString(length=36), nullable=False),
        sa.Column("scope_id", redteam_mcp.domain.storage.UUIDString(length=36), nullable=False),
        sa.Column("pattern", sa.String(length=256), nullable=False),
        sa.Column(
            "kind",
            sa.Enum(
                "HOSTNAME_EXACT",
                "HOSTNAME_WILDCARD",
                "HOSTNAME_APEX_WILDCARD",
                "CIDR_V4",
                "CIDR_V6",
                "IP_V4",
                "IP_V6",
                "URL_PATH",
                name="scope_entry_kind",
            ),
            nullable=False,
        ),
        sa.Column("included", sa.Boolean(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("added_by", redteam_mcp.domain.storage.UUIDString(length=36), nullable=True),
        sa.Column("added_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["scope_id"], ["scopes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scope_entries_scope_id"), "scope_entries", ["scope_id"], unique=False)
    op.create_table(
        "sessions",
        sa.Column("id", redteam_mcp.domain.storage.UUIDString(length=36), nullable=False),
        sa.Column(
            "engagement_id", redteam_mcp.domain.storage.UUIDString(length=36), nullable=False
        ),
        sa.Column("target_id", redteam_mcp.domain.storage.UUIDString(length=36), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "SLIVER",
                "HAVOC",
                "MSF",
                "COBALT_STRIKE",
                "SSH",
                "RDP",
                "LIGOLO_TUNNEL",
                name="session_kind",
            ),
            nullable=False,
        ),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("protocol", sa.String(length=32), nullable=False),
        sa.Column("callback_addr", sa.String(length=256), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "STALE", "LOST", "CLOSED", name="session_status"),
            nullable=False,
        ),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_check_in_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("remote_hostname", sa.String(length=256), nullable=True),
        sa.Column("remote_user", sa.String(length=256), nullable=True),
        sa.Column("remote_os", sa.String(length=128), nullable=True),
        sa.Column("remote_pid", sa.Integer(), nullable=True),
        sa.Column("remote_integrity", sa.String(length=32), nullable=True),
        sa.Column("credentials_used_json", sa.JSON(), nullable=False),
        sa.Column("findings_produced_json", sa.JSON(), nullable=False),
        sa.Column("artifacts_produced_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["engagement_id"], ["engagements.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["target_id"], ["targets.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sessions_engagement_id"), "sessions", ["engagement_id"], unique=False)
    op.create_index(op.f("ix_sessions_status"), "sessions", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_sessions_status"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_engagement_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_scope_entries_scope_id"), table_name="scope_entries")
    op.drop_table("scope_entries")
    op.drop_index(op.f("ix_findings_target_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_status"), table_name="findings")
    op.drop_index(op.f("ix_findings_severity"), table_name="findings")
    op.drop_index(op.f("ix_findings_engagement_id"), table_name="findings")
    op.drop_index(op.f("ix_findings_discovered_at"), table_name="findings")
    op.drop_table("findings")
    op.drop_index(op.f("ix_credentials_engagement_id"), table_name="credentials")
    op.drop_table("credentials")
    op.drop_index(op.f("ix_tool_invocations_tool_name"), table_name="tool_invocations")
    op.drop_index(op.f("ix_tool_invocations_started_at"), table_name="tool_invocations")
    op.drop_index(op.f("ix_tool_invocations_engagement_id"), table_name="tool_invocations")
    op.drop_index(op.f("ix_tool_invocations_actor_id"), table_name="tool_invocations")
    op.drop_table("tool_invocations")
    op.drop_index(op.f("ix_targets_value"), table_name="targets")
    op.drop_index(op.f("ix_targets_engagement_id"), table_name="targets")
    op.drop_table("targets")
    op.drop_table("scopes")
    op.drop_index(op.f("ix_artifacts_sha256"), table_name="artifacts")
    op.drop_index(op.f("ix_artifacts_engagement_id"), table_name="artifacts")
    op.drop_table("artifacts")
    op.drop_index(op.f("ix_engagements_name"), table_name="engagements")
    op.drop_table("engagements")
    # ### end Alembic commands ###
